default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: shopify_cancel_order_notifier
  username: postgres
  password: postgres

production:
  url: <%= ENV['DATABASE_URL'] %>
